
export const FETCH_LOGIN_ERROR = 'FETCH_LOGIN_ERROR';
export const FETCH_LOGIN_REQUEST = 'FETCH_LOGIN_REQUEST';
export const FETCH_LOGIN_SUCCESS = 'FETCH_LOGIN_SUCCESS';


export const UPDATE_LOGIN_ERROR = 'UPDATE_LOGIN_ERROR';
export const UPDATE_LOGIN_REQUEST = 'UPDATE_LOGIN_REQUEST';
export const UPDATE_LOGIN_SUCCESS = 'UPDATE_LOGIN_SUCCESS';


export const RESTORE_LOGIN_REQUEST = 'RESTORE_LOGIN_REQUEST';
export const RESTORE_LOGIN_SUCCESS = 'RESTORE_LOGIN_SUCCESS';

export const FETCH_USERPROFILE_SUCCESS = 'FETCH_USERPROFILE_SUCCESS';
export const FETCH_USERPROFILE_ERROR = 'FETCH_USERPROFILE_ERROR';
export const FETCH_USERPROFILE_REQUEST = 'FETCH_USERPROFILE_REQUEST';



export const FETCH_POSTDETAIL_SUCCESS = 'FETCH_POSTDETAIL_SUCCESS';
export const FETCH_POSTDETAIL_REQUEST = 'FETCH_POSTDETAIL_REQUEST';
export const FETCH_POSTDETAIL_ERROR = 'FETCH_POSTDETAIL_ERROR';

  

export const FETCH_POSTDETAILBOOKMARKUPDATE_SUCCESS = 'FETCH_POSTDETAILBOOKMARKUPDATE_SUCCESS';
export const FETCH_POSTDETAILBOOKMARKUPDATE_ERROR = 'FETCH_POSTDETAILBOOKMARKUPDATE_ERROR';
export const FETCH_POSTDETAILBOOKMARKUPDATE_REQUEST = 'FETCH_POSTDETAILBOOKMARKUPDATE_REQUEST';

  
export const FETCH_POSTDETAILFAVUPDATE_SUCCESS = 'FETCH_POSTDETAILFAVUPDATE_SUCCESS';
export const FETCH_POSTDETAILFAVUPDATE_REQUEST = 'FETCH_POSTDETAILFAVUPDATE_REQUEST';
export const FETCH_POSTDETAILFAVUPDATE_ERROR = 'FETCH_POSTDETAILFAVUPDATE_ERROR';


export const FETCH_REVIEWLISTING_ERROR = 'FETCH_REVIEWLISTING_ERROR';
export const FETCH_REVIEWLISTING_REQUEST = 'FETCH_REVIEWLISTING_REQUEST';
export const FETCH_REVIEWLISTING_SUCCESS = 'FETCH_REVIEWLISTING_SUCCESS';


export const FETCH_PACKAGEADD_ERROR = 'FETCH_PACKAGEADD_ERROR';
export const FETCH_PACKAGEADD_REQUEST = 'FETCH_PACKAGEADD_REQUEST';
export const FETCH_PACKAGEADD_SUCCESS = 'FETCH_PACKAGEADD_SUCCESS';
  
 
export const FETCH_PACKAGEDELETE_ERROR = 'FETCH_PACKAGEDELETE_ERROR';
export const FETCH_PACKAGEDELETE_REQUEST = 'FETCH_PACKAGEDELETE_REQUEST';
export const FETCH_PACKAGEDELETE_SUCCESS = 'FETCH_PACKAGEDELETE_SUCCESS';

export const FETCH_GUIDELISTING_ERROR='FETCH_GUIDELISTING_ERROR';
export const  FETCH_GUIDELISTING_REQUEST= 'FETCH_GUIDELISTING_REQUEST';
export const  FETCH_GUIDELISTING_SUCCESS= 'FETCH_GUIDELISTING_SUCCESS';
  
  export const FETCH_GUIDEADD_ERROR = 'FETCH_GUIDEADD_ERROR';
export const FETCH_GUIDEADD_REQUEST = 'FETCH_GUIDEADD_REQUEST';
export const FETCH_GUIDEADD_SUCCESS = 'FETCH_GUIDEADD_SUCCESS';
  
 
export const FETCH_GUIDEDELETE_ERROR = 'FETCH_GUIDEDELETE_ERROR';
export const FETCH_GUIDEDELETE_REQUEST = 'FETCH_GUIDEDELETE_REQUEST';
export const FETCH_GUIDEDELETE_SUCCESS = 'FETCH_GUIDEDELETE_SUCCESS';
  
 export const  FETCH_CATLISTING_SUCCESS='FETCH_CATLISTING_SUCCESS';
 export const FETCH_CATLISTING_REQUEST='FETCH_CATLISTING_REQUEST';
  export const FETCH_CATLISTING_ERROR='FETCH_CATLISTING_ERROR';

  export const  FETCH_USERUPDATE_SUCCESS='FETCH_USERUPDATE_SUCCESS';
  export const  FETCH_USERUPDATE_REQUEST='FETCH_USERUPDATE_REQUEST';
  export const FETCH_USERUPDATE_ERROR='FETCH_USERUPDATE_ERROR';


export const FETCH_PACKAGEUPDATE_SUCCESS='FETCH_PACKAGEUPDATE_SUCCESS';
export const FETCH_PACKAGEUPDATE_REQUEST='FETCH_PACKAGEUPDATE_REQUEST';
export const FETCH_PACKAGEUPDATE_ERROR='FETCH_PACKAGEUPDATE_ERROR';


	
export const FETCH_POSTLISTING_SUCCESS = 'FETCH_POSTLISTING_SUCCESS';
export const FETCH_POSTLISTING_REQUEST= 'FETCH_POSTLISTING_REQUEST';
export const FETCH_POSTLISTING_ERROR = 'FETCH_POSTLISTING_ERROR';

export const FETCH_FILTERPOSTLISTING_SUCCESS = 'FETCH_FILTERPOSTLISTING_SUCCESS';
export const FETCH_FILTERPOSTLISTING_REQUEST = 'FETCH_FILTERPOSTLISTING_REQUEST';
export const FETCH_FILTERPOSTLISTING_ERROR = 'FETCH_FILTERPOSTLISTING_ERROR';

export const REFRESH_POSTLISTING_REQUEST = 'REFRESH_POSTLISTING_REQUEST';

export const SEARCH_POSTLISTING_REQUEST = 'SEARCH_POSTLISTING_REQUEST';
export const SEARCH_POSTLISTING_ERROR = 'SEARCH_POSTLISTING_ERROR';
export const SEARCH_POSTLISTING_SUCCESS = 'SEARCH_POSTLISTING_SUCCESS';

export const FETCH_POSTADD_SUCCESS = 'FETCH_POSTADD_SUCCESS';
export const FETCH_POSTADD_REQUEST = 'FETCH_POSTADD_REQUEST';
export const FETCH_POSTADD_ERROR = 'FETCH_POSTADD_ERROR';

export const FETCH_POSTDELETE_SUCCESS = 'FETCH_POSTDELETE_SUCCESS';
export const FETCH_POSTDELETE_REQUEST = 'FETCH_POSTDELETE_REQUEST';
export const FETCH_POSTDELETE_ERROR = 'FETCH_POSTDELETE_ERROR';

export const FETCH_POSTUPDATE_SUCCESS = 'FETCH_POSTUPDATE_SUCCESS';
export const FETCH_POSTUPDATE_REQUEST = 'FETCH_POSTUPDATE_REQUEST';
export const FETCH_POSTUPDATE_ERROR = 'FETCH_POSTUPDATE_ERROR';

export const FETCH_POSTFAVUPDATE_ERROR = 'FETCH_POSTFAVUPDATE_ERROR';
export const FETCH_POSTFAVUPDATE_REQUEST = 'FETCH_POSTFAVUPDATE_REQUEST';
export const FETCH_POSTFAVUPDATE_SUCCESS = 'FETCH_POSTFAVUPDATE_SUCCESS';
  
  
export const  FETCH_FAVADD_SUCCESS='FETCH_FAVADD_SUCCESS';
export const  FETCH_FAVADD_REQUEST='FETCH_FAVADD_REQUEST';
export const  FETCH_FAVADD_ERROR='FETCH_FAVADD_ERROR';

export const FETCH_FAVLISTING_SUCCESS='FETCH_FAVLISTING_SUCCESS';
export const FETCH_FAVLISTING_REQUEST='FETCH_FAVLISTING_REQUEST';
export const FETCH_FAVLISTING_ERROR='FETCH_FAVLISTING_ERROR';
export const REFRESH_PACKAGELISTING_REQUEST='REFRESH_PACKAGELISTING_REQUEST';

export const SEARCH_STORELISTING_REQUEST="SEARCH_STORELISTING_REQUEST";
export const SEARCH_STORELISTING_ERROR="SEARCH_STORELISTING_ERROR";
export const SEARCH_STORELISTING_SUCCESS="SEARCH_STORELISTING_SUCCESS";


export const FETCH_PAYMENT_REQUEST="FETCH_PAYMENT_REQUEST";
export const FETCH_PAYMENT_ERROR="FETCH_PAYMENT_ERROR";
export const FETCH_PAYMENT_SUCCESS="FETCH_PAYMENT_SUCCESS";


export const  FETCH_BOOKMARKADD_SUCCESS='FETCH_BOOKMARKADD_SUCCESS';	
export const  FETCH_BOOKMARKADD_REQUEST='FETCH_BOOKMARKADD_REQUEST';
export const  FETCH_BOOKMARKADD_ERROR='FETCH_BOOKMARKADD_ERROR';

export const  FETCH_BOOKMARKLISTING_SUCCESS='FETCH_BOOKMARKLISTING_SUCCESS';
export const  FETCH_BOOKMARKLISTING_REQUEST='FETCH_BOOKMARKLISTING_REQUEST';
export const  FETCH_BOOKMARKLISTING_ERROR='FETCH_BOOKMARKLISTING_ERROR';

export const  FETCH_POSTBOOKMARKUPDATE_ERROR='FETCH_POSTBOOKMARKUPDATE_ERROR';
export const  FETCH_POSTBOOKMARKUPDATE_SUCCESS='FETCH_POSTBOOKMARKUPDATE_SUCCESS';
export const  FETCH_POSTBOOKMARKUPDATE_REQUEST='FETCH_POSTBOOKMARKUPDATE_REQUEST';
 

export const  FETCH_BLOCKUSERPOST_SUCCESS='FETCH_BLOCKUSERPOST_SUCCESS';
export const  FETCH_BLOCKUSERPOST_REQUEST='FETCH_BLOCKUSERPOST_REQUEST';
export const  FETCH_BLOCKUSERPOST_ERROR='FETCH_BLOCKUSERPOST_ERROR';


  
  
  
  	
export const FETCH_MYBOOKLISTING_ERROR="FETCH_MYBOOKLISTING_ERROR";
export const FETCH_MYBOOKLISTING_REQUEST="FETCH_MYBOOKLISTING_REQUEST";
export const FETCH_MYBOOKLISTING_SUCCESS="FETCH_MYBOOKLISTING_SUCCESS";


export const FETCH_MYBOOKDETAIL_ERROR="FETCH_MYBOOKDETAIL_ERROR";
export const FETCH_MYBOOKDETAIL_REQUEST="FETCH_MYBOOKDETAIL_REQUEST";
export const FETCH_MYBOOKDETAIL_SUCCESS="FETCH_MYBOOKDETAIL_SUCCESS";


export const FETCH_GIVEREVIEW_ERROR="FETCH_GIVEREVIEW_ERROR";
export const FETCH_GIVEREVIEW_REQUEST="FETCH_GIVEREVIEW_REQUEST";
export const FETCH_GIVEREVIEW_SUCCESS="FETCH_GIVEREVIEW_SUCCESS";
		
	
export const FETCH_PACKAGEFAVUPDATE_SUCCESS="FETCH_PACKAGEFAVUPDATE_SUCCESS";
export const FETCH_PACKAGEFAVUPDATE_ERROR="FETCH_PACKAGEFAVUPDATE_ERROR";


export const FETCH_NOTIFYLISTING_SUCCESS='FETCH_NOTIFYLISTING_SUCCESS';
export const FETCH_NOTIFYLISTING_REQUEST='FETCH_NOTIFYLISTING_REQUEST';
export const FETCH_NOTIFYLISTING_ERROR='FETCH_NOTIFYLISTING_ERROR';
	
export const FETCH_NOTIFYLISTUPDATE_SUCCESS='FETCH_NOTIFYLISTUPDATE_SUCCESS';
export const  FETCH_NOTIFYLISTUPDATE_REQUEST='FETCH_NOTIFYLISTUPDATE_REQUEST';
export const  FETCH_NOTIFYLISTUPDATE_ERROR='FETCH_NOTIFYLISTUPDATE_ERROR';

export const FETCH_COMMENTADD_SUCCESS='FETCH_COMMENTADD_SUCCESS';
export const FETCH_COMMENTADDD_REQUEST='FETCH_COMMENTADDD_REQUEST';
export const FETCH_COMMENTADD_ERROR='FETCH_COMMENTADD_ERROR';

export const FETCH_COMMENTLISTING_SUCCESS='FETCH_COMMENTLISTING_SUCCESS';
export const FETCH_COMMENTLISTING_REQUEST='FETCH_COMMENTLISTING_REQUEST';
export const FETCH_COMMENTLISTING_ERROR='FETCH_COMMENTLISTING_ERROR';

export const FETCH_COMMENTRESET_SUCCESS='FETCH_COMMENTRESET_SUCCESS';

export const FETCH_FRIENDADD_SUCCESS='FETCH_FRIENDADD_SUCCESS';
export const  FETCH_FRIENDADD_REQUEST='FETCH_FRIENDADD_REQUEST';
export const  FETCH_FRIENDADD_ERROR='FETCH_FRIENDADD_ERROR';	

export const FETCH_FRIENDREQUESTSEND_ERROR='FETCH_FRIENDREQUESTSEND_ERROR';
export const  FETCH_FRIENDREQUESTSEND_SUCCESS='FETCH_FRIENDREQUESTSEND_SUCCESS';
export const  FETCH_FRIENDREQUESTSEND_REQUEST='FETCH_FRIENDREQUESTSEND_REQUEST';	
  
export const FETCH_FRIENDREQUESTDELETE_REQUEST='FETCH_FRIENDREQUESTDELETE_REQUEST';
export const  FETCH_FRIENDREQUESTDELETE_SUCCESS='FETCH_FRIENDREQUESTDELETE_SUCCESS';
export const  FETCH_FRIENDREQUESTDELETE_ERROR='FETCH_FRIENDREQUESTDELETE_ERROR';  
  	
export const FETCH_FRIENDREQUESTUPDATE_REQUEST='FETCH_FRIENDREQUESTUPDATE_REQUEST';
export const  FETCH_FRIENDREQUESTUPDATE_SUCCESS='FETCH_FRIENDREQUESTUPDATE_SUCCESS';
export const  FETCH_FRIENDREQUESTUPDATE_ERROR='FETCH_FRIENDREQUESTUPDATE_ERROR';  

  // nidhi
export const FETCH_POSTCOMMENTRESET_SUCCESS='FETCH_POSTCOMMENTRESET_SUCCESS';  
export const  RESET_NOTIFYLISTING='RESET_NOTIFYLISTING';
    
  // frirend req denied
export const	FETCH_FRIENDDELETE_SUCCESS='FETCH_FRIENDDELETE_SUCCESS';
export const  FETCH_FRIENDDELETE_REQUEST='FETCH_FRIENDDELETE_REQUEST';
export const  FETCH_FRIENDDELETE_ERROR='FETCH_FRIENDDELETE_ERROR';


export const  FETCH_CHATROOMLISTING_SUCCESS='FETCH_CHATROOMLISTING_SUCCESS';
export const  FETCH_CHATROOMLISTING_REQUEST='FETCH_CHATROOMLISTING_REQUEST';
export const  FETCH_CHATROOMLISTING_ERROR='FETCH_CHATROOMLISTING_ERROR';


export const  CREATE_CHATMESSAGE_ERROR='CREATE_CHATMESSAGE_ERROR';
export const  CREATE_CHATMESSAGE_REQUEST='CREATE_CHATMESSAGE_REQUEST';
export const  CREATE_CHATMESSAGE_SUCCESS='CREATE_CHATMESSAGE_SUCCESS';


export const  FETCH_CHATMESSAGELISTING_ERROR='FETCH_CHATMESSAGELISTING_ERROR';
export const  FETCH_CHATMESSAGELISTING_SUCCESS='FETCH_CHATMESSAGELISTING_SUCCESS';
export const  FETCH_CHATMESSAGELISTING_REQUEST='FETCH_CHATMESSAGELISTING_REQUEST';


export const  UPDATE_CHATMESSAGE_ERROR='UPDATE_CHATMESSAGE_ERROR';
export const  UPDATE_CHATMESSAGE_REQUEST='UPDATE_CHATMESSAGE_REQUEST';
export const  UPDATE_CHATMESSAGE_SUCCESS='UPDATE_CHATMESSAGE_SUCCESS';

export const FETCH_COMMENTDEL_SUCCESS='FETCH_COMMENTDEL_SUCCESS';
export const FETCH_COMMENTDEL_REQUEST='FETCH_COMMENTDEL_REQUEST';
export const FETCH_COMMENTDEL_ERROR='FETCH_COMMENTDEL_ERROR';
  
    
  
  



  
  
  
  